name: Deploy to production Environment

on:
  pull_request:
    types: [closed] 
    branches: [main]

jobs:
  build_docker_image:
    if: github.event.pull_request.merged == true
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: edit .env file
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST_PROD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI_PROD }}
          REDIS_URL: ${{ secrets.REDIS_URL_PROD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER_PROD }}
        run: |
          echo "PORT=${PORT}" > .env
          echo "HOST=${HOST}" >> .env
          echo "MONGODB_URI=${MONGODB_URI}" >> .env
          echo "REDIS_URL=${REDIS_URL}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "EMAIL_USER=${EMAIL_USER}" >> .env
          echo "EMAIL_PASS=${EMAIL_PASS}" >> .env
          echo "KAFKA_BROKER=${KAFKA_BROKER}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub pass-code-sender
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: byvoxel/auth-pass-code-sender
          tags: |
            type=raw,value=production
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: byvoxel/auth-pass-code-sender:production
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-52-202-22-209.compute-1.amazonaws.com

    steps:
      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY_PROD1 }}
          port: 22
          timeout: "120s"
          script: |
            set -e
            echo "Deploying image: byvoxel/auth-pass-code-sender:production"
            sudo docker stop auth-pass-code-sender || true
            sudo docker rm auth-pass-code-sender || true
            sudo docker pull byvoxel/auth-pass-code-sender:production
            sudo docker run -d \
              --name auth-pass-code-sender \
              -p 3012:3012 \
              --restart unless-stopped \
              byvoxel/auth-pass-code-sender:production
            sudo docker system prune -af --volumes || true